# name:jenkins-inbound-agent-docker

# FROM jenkins/inbound-agent

# USER root

# # Add Docker's official GPG key:
# RUN apt-get update
# RUN apt-get install -y ca-certificates curl gnupg
# RUN install -m 0755 -d /etc/apt/keyrings
# RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
# RUN chmod a+r /etc/apt/keyrings/docker.gpg

# # Add the repository to Apt sources:
# RUN echo \
#   "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
#   "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
#   tee /etc/apt/sources.list.d/docker.list > /dev/null
# RUN apt-get update

# # To install the latest version, run
# RUN apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
# RUN service docker start

# # Agregar el usuario jenkins al grupo docker
# RUN usermod -aG docker jenkins

# USER jenkins



FROM ghcr.io/cirruslabs/flutter:3.13.0

USER root

ENV JENKINS_URL=JENKINS_URL__
ENV JENKINS_AGENT_NAME=JENKINS_AGENT_NAME__
ENV JENKINS_AGENT_WORKDIR=JENKINS_AGENT_WORKDIR__
ENV JENKINS_SECRET=JENKINS_SECRET__

RUN sudo apt update \
  && apt install -y default-jdk curl curl gnupg

RUN echo $JENKINS_URL

RUN curl -sO $JENKINS_URL/jnlpJars/agent.jar

RUN java -jar agent.jar -jnlpUrl \
    && $JENKINS_URL/computer/$JENKINS_AGENT_NAME/jenkins-agent.jnlp\
    &&  -secret $JENKINS_SECRET -workDir "$JENKINS_AGENT_WORKDIR"


USER jenkins
