# name:jenkins-inbound-agent-docker


RUN  apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release 
RUN  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg 
RUN  echo \
    "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null 
RUN  apt-get update 
RUN  apt-get install -y docker-ce docker-ce-cli containerd.io

RUN usermod -aG docker jenkins

USER jenkins




FROM jenkins/inbound-agent

USER root

# Instalar dependencias necesarias
RUN apt-get update \
    && apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Instalar Docker según la documentación oficial
RUN curl -fsSL https://get.docker.com | sh

# Agregar el usuario jenkins al grupo docker
RUN usermod -aG docker jenkins

USER jenkins